### ISSUE TITLE
:trophy: Implémentation de tous les écrans

### ISSUE THREAD

**Issue by adriens** [adriens/temps-attente-matrix-led#21]
# :dart: Actions

- [x] Ecran de boot amélioré - [ ] #30 
- [x] Ecran des logos - [ ] #30 
- [x] Ecran de la légende - [ ] #30 
- [x] Ecran d'affichage optimisé et enrichi - [ ] #30 
- [x] Ecran POC QrCode
- [x] Implémentation du flow entre les écrans  - [ ] #30 
![image](https://github.com/user-attachments/assets/2aeb205c-b623-4b31-9b00-fee1d45a96e2)

# :camera_flash: Ressources

![image](https://github.com/user-attachments/assets/664da33e-d3a4-4a5e-a893-ed51eefab048)

**Comment by raphb3383** [comment]
- [ ] #30

**Comment by raphb3383** [comment]
J'ai mis à jour le script afin de pouvoir avoir :
1/ Ecran d'accueil
2/ Ecran information
3/ Ecran de légendes
4/ Ecran Temps attente agences
5/ QR CODE

https://github.com/user-attachments/assets/5ec19232-05f1-44a0-b53e-e9578fe0e39b


@adriens @josegoue993

**Comment by adriens** [comment]
:clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :star_struck:
