### ISSUE TITLE
DoD

### ISSUE THREAD

**Issue by raphb3383** [adriens/temps-attente-matrix-led#34]
(Definition of Done)
 
 Regroupement des différentes objectifs de réalisation du projet (niveau paramétrage matrice LED).
 

**Script "main" (DEF et boucle)**
  - [x] Affichage des différents screens (Acceuil, Information, Légende, Agences) - [ ] #21  
  -  [x] Regroupement des informations dans un fichier .env
  - [x] Synchronisation NTP 
  - [x] Connexion WiFi

**Screen "Acceuil"**  - [ ] #31  
  - [x] Logo UNC
  - [x] Logo OPT
  - [x] Animation

**Screen "Information"**
  - [x] Visualisation état WIFI
  -  [x] Visualisation lecture clé API
  - [x] Adresse bit-ly - [ ] #22  
  - [x] Optimisation de la typologie

**Screen "Légende"**
  - [x] Définition des icônes de l'affichage "Agences"
  - [x] Optimisation de la typologie

**Screen "Agences"**
  - [x] Affichage type 3 blocs & charte graphique - [ ] #9 
- Bloc1 - [ ] #10 
  - [x] Logo OPT avec couleur OPT
  - [x] Heure synchronisée NTP
- Bloc2 - [ ] #11 
  - [x] Affichage symbolique permettant d'afficher l'attente en agence
  - [x] Icônes fonctionnels 
  - - [x] Son (On/Off)
  - - [x] Wifi (KO)
  - -  [x] Boucle (affichage figé ou non sur une agence)
  - -  [x] Synthèse temps attente
- Bloc3 - [ ] #12 
  -  [x] Scrolling nom d'agence en cours d'affichage

**Script "main_loop" (DEF et boucle)**
  -  [x] API CSV pour la récupération initiale des données des agences
  -  [x] API JSON/DATA  pour la mise à jour de ces données
  -  [x] Boucle affichage sur agence
  -  [x] Fonctionnalités physique
  -  [x] Sortie propre du script sur erreur/arrêt

**Comment by adriens** [comment]
@raphb3383 @josegoue993 , je sors d'une réunion avec Nazha à l'instant. Deux news : 

1. La soutenance finale avec démo sera la semaine prochaine : je n'ai pas la date ni l'heure encore
2. J'assurerai la vacation sur interop data et urba des SIs
